//LOCAL HOST
### Get all employees
GET http://localhost:8080/employees

### Get all contacts by id
GET http://localhost:8080/employees/6528be21c62ca7750fa721b1

### create employee
POST http://localhost:8080/employees HTTP/1.1
content-type: application/json

{
    "firstName": "Harry",
    "lastName": "Clarke",
    "position": "Campus Recruiter",
    "department": "HR",
    "gender": "Male",
    "dob": "09/20/2004",
    "phoneNumber": "2071234444",
    "startDate": "12/11/2022"
}

### update employee
PUT http://localhost:8080/employees/6528c947e477812b3cb63229 HTTP/1.1
content-type: application/json

{
    "firstName": "Harry",
    "lastName": "Clarke",
    "position": "Campus Recruiter",
    "department": "HR",
    "gender": "Male",
    "dob": "09/20/2006"
}

### Delete contact
DELETE http://localhost:8080/employees/653d65f8b8c3f92347845d4d HTTP/1.1

//PRODUCTION
### Get all employees
GET https://narah-employee-management.onrender.com/employees

### Get all contacts by id
GET http://localhost:8080/employees/6528be21c62ca7750fa721b1

### create employee
POST https://narah-employee-management.onrender.com/employees HTTP/1.1
content-type: application/json

{
    "firstName": "Harry",
    "lastName": "Clarke",
    "position": "Campus Recruiter",
    "department": "HR",
    "gender": "Male",
    "dob": "09/20/2004"
}

### update employee
PUT https://narah-employee-management.onrender.com/employees/6528be21c62ca7750fa721b1 HTTP/1.1
content-type: application/json

{
    "firstName": "Harry",
    "lastName": "Clarke",
    "position": "Campus Recruiter",
    "department": "HR",
    "gender": "Male",
    "dob": "09/20/2006"
}

### Delete contact
DELETE https://narah-employee-management.onrender.com/employees/6528be21c62ca7750fa721b1 HTTP/1.1